# Generated by Django 4.1.1 on 2022-09-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter equity name', max_length=255)),
                ('ticker', models.CharField(help_text='Enter ticker name', max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sector', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('employees_count', models.IntegerField()),
                ('sic_no', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('exchange', models.IntegerField(null=True)),
                ('cik_no', models.IntegerField(null=True)),
                ('cusip', models.IntegerField(null=True)),
                ('currency', models.IntegerField()),
                ('data_source_id', models.IntegerField()),
                ('ckr_log', models.CharField(max_length=255)),
                ('similar_fund_log', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=13)),
                ('website', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(choices=[(True, 't'), (False, 'f')])),
                ('url_slug', models.CharField(max_length=255)),
                ('delisted_date', models.DateField(null=True)),
                ('delisted_reason', models.TextField()),
                ('image_name', models.CharField(max_length=255)),
                ('image_aspect_ratio', models.FloatField(default=1)),
                ('cumulative_return_update', models.DateTimeField()),
            ],
        ),
    ]
