# Generated by Django 4.1.1 on 2022-09-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equity',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='equity',
            old_name='currency',
            new_name='currency_id',
        ),
        migrations.RenameField(
            model_name='equity',
            old_name='exchange',
            new_name='exchange_id',
        ),
        migrations.AlterField(
            model_name='equity',
            name='url_slug',
            field=models.SlugField(max_length=128),
        ),
    ]
