# Generated by Django 4.1.1 on 2022-09-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_company_equity_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equity',
            name='cumulative_return_update',
            field=models.DateTimeField(null=True),
        ),
    ]
