# Generated by Django 4.1.1 on 2022-09-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_equity_cumulative_return_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equity',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='equity',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
