# Generated by Django 4.1.1 on 2022-09-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_equity_employees_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equity',
            name='currency_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='equity',
            name='data_source_id',
            field=models.IntegerField(null=True),
        ),
    ]
