# Generated by Django 4.1.1 on 2022-09-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_equity_currency_id_alter_equity_data_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equity',
            name='delisted_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equity',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
