# Generated by Django 4.1.1 on 2022-09-16 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_equity_delisted_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equity',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='DailyReturns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('returns', models.FloatField(default=0.0)),
                ('open', models.FloatField(default=0.0)),
                ('high', models.FloatField(default=0.0)),
                ('low', models.FloatField(default=0.0)),
                ('close', models.FloatField(default=0.0)),
                ('adj_close', models.FloatField(default=0.0)),
                ('equity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equity')),
            ],
        ),
    ]
